### ISSUE TITLE
worker crash

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#322]
neal-desktop:~/maelstrom[130]% cargo run --release --bin maelstrom-worker
    Finished `release` profile [optimized] target(s) in 0.23s
     Running `target/release/maelstrom-worker`
Jun 27 22:03:33.567 INFO started, pid: 2, config: Config { broker: 127.0.0.1:1234, slots: 8, cache_root: "/home/neal/.cache/maelstrom/worker/", cache_size: 20.0 GB, inline_limit: 1000.0 KB, log_level: Info }
thread 'thread '<unnamed><unnamed>' panicked at ' panicked at crates/maelstrom-util/src/io.rscrates/maelstrom-util/src/io.rs::945945::99:
:
assertion `left == right` failed
  left: 778982
 right: 1048576assertion `left == right` failed
  left: 249856
 right: 1048576

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  cargo run --release --bin maelstrom-worker

**Comment by bobbobbio** [comment]
It looks like this failed doing a short write to the pipe via splice. Something I thought couldn't happen at the time for some reason

**Comment by bobbobbio** [comment]
wow actually it kinda looks like this happened twice at once.  That probably means this was the path where we are download artifacts.

So yeah, here is a theory about this, perhaps this happens when your file-system is full. That would explain hitting this multiple times at once and you had mentioned you had that problem. That should be easy to fix, I'll just throw an error.
