### ISSUE TITLE
Update `fancy` UI to only start the clock on tests when they start executing.

### ISSUE THREAD

**Issue by nfachan** [maelstrom-software/maelstrom#379]
I'm not sure what we should do with tests that haven't started executing yet. One option is to keep them in the same window as the executing tests, but to change the counter to a word that represents the state. These would then sort below the currently-executing tests in the window.

Another option is to summarize this information somewhere else and to not have waiting tests listed in the executing window.

I guess we'll just have to see which looks betters.

**Definition of Done**
- [x] `CHANGELOG.md` updated.
- [x] Issue is in the correct milestone.

**Comment by nfachan** [comment]
Depends on #64.

**Comment by bobbobbio** [comment]
> I'm not sure what we should do with tests that haven't started executing yet.
I gave it some thought and I'm not sure what to do about them either.
Mixing them in with the running jobs I don't like that much mostly because to me it weakens the meaning of the running dialog.
Having their own dialog for them can really clutter things and the way the viewport is we don't have a ton of vertical space.

I think maybe it needs more thought / discussion about the situation where we want to know which jobs are pending, so I wish to split out some other issue for dealing with that and close this one.
